config/routes.rb
Linkvan::Application.routes.draw do

  get 'api/facilities', to: 'api#all' #only enable if needed
  get 'api/facilities/filter/:scope', to: 'api#filtered'
  get 'api/facilities/filteredtest', to: 'api#filteredtest'
  get 'api/facilities/search', to: 'api#search'
  get 'api/facilities/:id', to: 'api#show'
  get 'api/getchanges', to: "api#getchanges"

  get "contact_form/new"
  get "contact_form/create"
  resource :session
  resources :users

  get 'facilities/options', to: 'facilities#options'
  get 'facilities/directions/:id', to: 'facilities#directions'
  get "facilities/filter/:scope" => "facilities#filtered", as: :filtered_facilities
  get 'facilities/filter/:scope/:latitude&:longitude', to: 'facilities#filtered', as: :coords_facilities
  get 'facilities/filter/:scope/:latitude&:longitude&:sortby&:hours&:services&:suitable&:welcome', to: 'facilities#filtered', as: :searched_facilities
  get 'facilities/search', to: 'facilities#search', as: :search_bar_facilities
  get 'crisis', to: 'crisis#index'
  get 'disclaimer', to: 'disclaimer#index'
  get 'about', to: 'about#index'
  get 'images', to: 'images#index'
  root 'facilities#index'
  get 'signup' => 'users#new'
  get "signin" => "sessions#new"
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  resources :facilities

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :facilities

  validates :name, presence: true
  validates :email, presence: true,
  					format: /\A\S+@\S+\z/,
  					uniqueness: { case_sensitive: false}

  def self.authenticate(email, password)
  	user = User.find_by(email: email)
	  user && user.authenticate(password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_admin, only: [:index]
  before_action :require_correct_user_or_admin, only: [:edit, :update, :show, :destroy]  

	def index
		@users = User.all
	end

	def show
    @message = Message.new
    @user = User.find(params[:id])
	end

	def new
  	@user = User.new
	end

	def create
  		@user = User.new(user_params)
  		if @user.save
        session[:user_id] = @user.id
    		redirect_to @user, notice: "Thanks for signing up!"
        UserMailer.welcome_email(@user).deliver
  		else
    		render :new
  		end
	end

	def edit
    @user = User.find(params[:id])
	end

	def update
    @user = User.find(params[:id])
 		if @user.update(user_params)
    	redirect_to @user, notice: "Account successfully updated!"
  	else
    	render :edit
  	end
	end

	def destroy
      @user = User.find(params[:id])
  		@user.facilities.each do |f|
        f.user = nil
        f.save
      end
      @user.destroy
      if session[:user_id] == @user.id
        session[:user_id] = nil #session[:user_id] = nil
      end
      
  		redirect_to root_url, alert: "Account successfully deleted!"
	end

	private

	def user_params
  		params.require(:user).
    	permit(:name, :email, :password, :password_confirmation, :activation_email_sent)
	end

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
    end
  end






end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <fieldset>
    <ul>
      <li class="required">
        <%= f.label :name %><br>
        <%= f.text_field :name, size: 40 %><br>
      </li>
      <li class="required">
        <%= f.label :email %><br>
        <%= f.email_field :email, size: 40 %><br>
      </li>
      <li class="required">
        <%= f.label :password %><br>
        <%= f.password_field :password, size: 40 %><br>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %><br>
        <%= f.password_field :password_confirmation, size: 40 %><br>
      </li>
    </ul><br>

      <%= f.submit %>

  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render 'facilities/nav' %>
<h1 style="text-align: center; margin-top: 50px; margin-bottom: -30px; font-weight: bold">Editing User Account Info</h1>

<div id="index-main">
	<div class="edit-form">
		<%= render 'form' %>
	</div>
</div>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= render 'facilities/nav' %>
<h1 style="text-align: center; margin-top: 50px; margin-bottom: -30px; font-weight: bold">Service Provider Sign Up</h1>
<div class="profile">
  <h4>Are you a Service Provider in the Vancouver DTES offering one or more services in any of the following categories: Shelter, Food, Medical, Hygiene, Technology, or Advocacy? If so, you're on the right page! Creating a LinkVan account allows you to update the content on your organization's page in the web app. In addition, we provide you basic analytics data for your account.<br><br>
  <h4>Activating an account is easy and absolutely free!<br><br>
  <ul>
  	<li><b>Step 1:</b> Fill out the form below to set your password and click Create User.</li><br>

  	<li><b>Step 2:</b> Tell us if you'd like to create a new listing for your organization OR become the administrator of your organization's page if it's already in the web app.</li><br>

  	<li><b>Step 3:</b> A member of our team will get in touch with you over the phone as soon as we can to verify your account and help with the initial set up.</li>
  </ul><br>

  And that's it! Should you have any questions, please reach out to us at <%= mail_to("info@linkvan.ca", "info@linkvan.ca") %>.</h4><br>

<div class="sign-up-form">
	<%= render 'form' %>
</div>
<hr>
<div class="quote">
  	<p>"Teamwork is the ability to work together toward a common vision. The ability to direct individual accomplishments toward organizational objectives. It is the fuel that allows common people to attain uncommon results." — Andrew Carnegie</p>
</div>
</div>

app/views/users/show.html.erb
<%= render 'facilities/nav' %>
<div class="profile">

  <h1><%= @user.name %></h1>
  <h4><%= mail_to(@user.email) %></h4>

<h4>Registered Since <%= @user.created_at.strftime("%B %Y") %></h4>

<br>


<% @imps = Array.new %>
<% @facilitynames = Array.new %>

<!--if @user.facilities.count > 0-->
<% if @user.facilities.count > 0 %>
  <div class="administered">
    <h4><%= pluralize(@user.facilities.count, 'Facility') %> Available to Edit</h4>
    <ul>
      <% @user.facilities.each do |f| %>
        <li><%= link_to f.name, edit_facility_path(f.id) %>  (Monthly View Count: <%= Impression.where(impressionable_id: f.id).count %>)</li>

      <% @imps.concat(Impression.where(impressionable_id: f.id)) %>
      <% @facilitynames.push(f.name) %>
      <% end %>
    </ul>
  </div>


<br>
<div class="report">
 <!--Div that will hold the dashboard-->
  <h4>Reports</h4>
    <div id="dashboard_div">
      <!--Divs that will hold each control and chart-->
      
      <div id="chart_div"></div>
      <div id="filter_div"></div>
    </div>


    <div id="day_of_week_div"></div>

    <div id="time_of_day_div"></div>
</div>
<%elsif @user.activation_email_sent%>
  <h3>Thank you! Your message has already been sent to the LinkVan team. We will get in touch as soon as we can :)</h3>

<%else%>
  <h4><b>Step 2: </b>Almost ready! Please fill out the form below and a member of the LinkVan team will get in touch with you as soon as we can to finish setting up your account:</h4><br>

  <%= render 'messages/contact_form' %>


<%end%>

<br>



<footer>

    <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
    |
    <%= link_to 'Delete Account', @user,
                method: :delete,
                data: { confirm: 'Are you sure you want to permanently delete your account?' }%>

</footer>

</div>

<%= content_tag :div, class: "temp_information", data: {facilitynames: @facilitynames, imps: @imps} do %>
<% end %>

  <!--Load the AJAX API-->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">


var facilitynames = $('.temp_information').data('facilitynames');
var imps = $('.temp_information').data('imps');

function dateMinus(date, type, amount){
    var y = date.getFullYear(),
        m = date.getMonth(),
        d = date.getDate();
    if(type === 'y'){
        y -= amount;
    };
    if(type === 'm'){
        m -= amount;
    };
    if(type === 'd'){
        d -= amount;
    };
    return new Date(y, m, d);
}

function dateAdd(date, type, amount){
    var y = date.getFullYear(),
        m = date.getMonth(),
        d = date.getDate();
    if(type === 'y'){
        y += amount;
    };
    if(type === 'm'){
        m += amount;
    };
    if(type === 'd'){
        d += amount;
    };
    return new Date(y, m, d);
}

function compareDates(date1, date2){
  if ((date1.getFullYear() == date2.getFullYear()) && (date1.getMonth() == date2.getMonth()) && (date1.getDate() == date2.getDate())){
    return true;
  }else{
    return false;
  }
}


function initializeRow(rowNum){
  masterData.push([new Date(minDate.toString())]);

  for(var i=0; i<facilitynames.length; i++){
    masterData[rowNum].push(0);
  }
}

function incHour(hour, k){
  masterDataTimeOfDay[hour+1, k+1]++;
}

var maxDaysAgo = 30;
var minDate = dateMinus(new Date(), 'd', maxDaysAgo);
var masterData = [];
var masterDataDayOfWeek = [];
var masterDataTimeOfDay = [];
//initialize first row of masterData
var firstRow = ["Date"];
var firstRowDayOfWeek = ["Day of Week"];
var firstRowTimeOfDay = ["Time of Day"];

for(var i=0; i<facilitynames.length; i++){
  firstRow.push(facilitynames[i]);
  firstRowDayOfWeek.push(facilitynames[i]);
  firstRowTimeOfDay.push(facilitynames[i]);
}
masterData.push(firstRow);
masterDataDayOfWeek.push(firstRowDayOfWeek);
masterDataTimeOfDay.push(firstRowTimeOfDay);

//build masterData for first report
/* output:
[['Date',         'FacName1', 'FacName2', ...],
  ['Jan 1, 2016',  0,          20],
  ['Jan 2, 2016',  25,         46],
  ['Jan 3, 2016',  3,          5],
  ['Jan 4, 2016',  10,         4],
  ...] */
for(var i=0; i<=maxDaysAgo; i++){
  initializeRow(i+1);
  for(var j=0; j<imps.length; j++){
    if (compareDates(minDate, new Date(imps[j].created_at))){
      for(var k=0; k<facilitynames.length; k++){
        if (imps[j].message == facilitynames[k]){
          masterData[i+1][k+1]++;
        }
      }
    }
  }
  minDate = dateAdd(minDate, 'd', 1);
}


//build masterDataDayOfWeek for 2nd report
/* output:
[['Day of Week', 'FacName1', 'FacName2', ...],
  [Mon,        ,  0,          5],
  [Tues,       ,  4,          15],
  ...] */

masterDataDayOfWeek.push(["Mon"]);
masterDataDayOfWeek.push(["Tues"]);
masterDataDayOfWeek.push(["Wed"]);
masterDataDayOfWeek.push(["Thurs"]);
masterDataDayOfWeek.push(["Fri"]);
masterDataDayOfWeek.push(["Sat"]);
masterDataDayOfWeek.push(["Sun"]);


for(var i=0; i<7; i++){
  for(var j=0; j<facilitynames.length; j++){
    masterDataDayOfWeek[i+1].push(0);
  }
}


for(var j=0; j<imps.length; j++){
  for(var k=0; k<facilitynames.length; k++){
  switch (new Date(imps[j].created_at).getDay()) {
    case 0:
        //Sunday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[7][k+1]++;
        }
        break;
    case 1:
        //Monday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[1][k+1]++;
        }
        break;
    case 2:
        //Tuesday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[2][k+1]++;
        }
        break;
    case 3:
        //Wednesday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[3][k+1]++;
        }
        break;
    case 4:
        //Thursday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[4][k+1]++;
        }
        break;
    case 5:
        //Friday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[5][k+1]++;
        }
        break;
    case 6:
        //Saturday
        if (imps[j].message == facilitynames[k]){
          masterDataDayOfWeek[6][k+1]++;
        }
        break;
  }
}
}

//build masterTimeOfDay for 3rd report
/* output:
[['Time Of Day', 'FacName1', 'FacName2', ...],
  [00,        ,   0,          5],
  [01,       ,    4,          15],
  ...] */

    //console.log(new Date(imps[2].created_at));
    //console.log(Number(new Date(imps[2].created_at).toString().substring(16, 18)));
    
masterDataTimeOfDay.push(["12am-1am"]);
masterDataTimeOfDay.push(["1am-2am"]);
masterDataTimeOfDay.push(["2am-3am"]);
masterDataTimeOfDay.push(["3am-4am"]);
masterDataTimeOfDay.push(["4am-5am"]);
masterDataTimeOfDay.push(["5am-6am"]);
masterDataTimeOfDay.push(["6am-7am"]);
masterDataTimeOfDay.push(["7am-8am"]);
masterDataTimeOfDay.push(["8am-9am"]);
masterDataTimeOfDay.push(["9am-10am"]);
masterDataTimeOfDay.push(["10am-11am"]);
masterDataTimeOfDay.push(["11am-12pm"]);
masterDataTimeOfDay.push(["12pm-1pm"]);
masterDataTimeOfDay.push(["1pm-2pm"]);
masterDataTimeOfDay.push(["2pm-3pm"]);
masterDataTimeOfDay.push(["3pm-4pm"]);
masterDataTimeOfDay.push(["4pm-5pm"]);
masterDataTimeOfDay.push(["5pm-6pm"]);
masterDataTimeOfDay.push(["6pm-7pm"]);
masterDataTimeOfDay.push(["7pm-8pm"]);
masterDataTimeOfDay.push(["8pm-9pm"]);
masterDataTimeOfDay.push(["9pm-10pm"]);
masterDataTimeOfDay.push(["10pm-11pm"]);
masterDataTimeOfDay.push(["11pm-12am"]);



for(var i=0; i<24; i++){
  for(var j=0; j<facilitynames.length; j++){
    masterDataTimeOfDay[i+1].push(0);
  }
}


for(var j=0; j<imps.length; j++){
  for(var k=0; k<facilitynames.length; k++){
    var test = new Date(imps[j].created_at).toString().substring(16, 18);
    console.log(test)
  switch (Number(new Date(imps[j].created_at).toString().substring(16, 18))){
    case 0:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[1][k+1]++;
        }
        break;
    case 1:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[2][k+1]++;
        }
        break;
    case 2:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[3][k+1]++;
        }
        break;
    case 3:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[4][k+1]++;
        }
        break;
    case 4:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[5][k+1]++;
        }
        break;
    case 5:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[6][k+1]++;
        }
        break;
    case 6:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[7][k+1]++;
        }
        break;
    case 7:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[8][k+1]++;
        }
        break;
    case 8:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[9][k+1]++;
        }
        break;
    case 9:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[10][k+1]++;
        }
        break;
    case 10:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[11][k+1]++;
        }
        break;
    case 11:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[12][k+1]++;
        }
        break;
    case 12:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[13][k+1]++;
        }
        break;
    case 13:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[14][k+1]++;
        }
        break;
    case 14:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[15][k+1]++;
        }
        break;
    case 15:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[16][k+1]++;
        }
        break;
    case 16:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[17][k+1]++;
        }
        break;
    case 17:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[18][k+1]++;
        }
        break;
    case 19:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[20][k+1]++;
        }
        break;
    case 20:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[21][k+1]++;
        }
        break;
    case 21:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[22][k+1]++;
        }
        break;
    case 22:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[23][k+1]++;
        }
        break;
    case 23:
        if (imps[j].message == facilitynames[k]){
          masterDataTimeOfDay[24][k+1]++;
        }
        break;
  }
  }
}

      // Load the Visualization API and the controls package.
      google.load('visualization', '1.0', {'packages':['controls', 'corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawDashboard);
      

      // Callback that creates and populates a data table,
      // instantiates a dashboard, a range slider and a pie chart,
      // passes in the data and draws it.


      function drawDashboard() {

        var data = new google.visualization.arrayToDataTable(masterData);
        var dataDayOfWeek = new google.visualization.arrayToDataTable(masterDataDayOfWeek);
        var dataTimeOfDay = new google.visualization.arrayToDataTable(masterDataTimeOfDay);
        

        // Create a dashboard.
        var dashboard = new google.visualization.Dashboard(
            document.getElementById('dashboard_div'));

        var chartDayOfWeek = new google.visualization.ColumnChart(document.getElementById('day_of_week_div'));

        var chartTimeOfDay = new google.visualization.BarChart(document.getElementById('time_of_day_div'));


        // Create a range slider, passing some options
        var dateRangeSlider = new google.visualization.ControlWrapper({
          'controlType': 'DateRangeFilter',
          'containerId': 'filter_div',
          'options': {
            'filterColumnIndex': '0',
            'filterColumnLabel': 'Date'
          }
        });

        var optionsDayOfWeek = {
          title: 'Number of Views per Day of Week',
          curveType: 'linear',
          legend: { position: 'right' },
          'width': 650,
          'height': 402
        };

        var optionsTimeOfDay = {
          title: 'Number of Views per Time of Day',
          curveType: 'linear',
          legend: { position: 'right' },
          'width': 650,
          'height': 800
        };

        // Create a pie chart, passing some options
        var lineChart = new google.visualization.ChartWrapper({
          'chartType': 'ColumnChart',
          'containerId': 'chart_div', 
          'options': {
            'title' : 'Number of Views per Day',
            'width': 650,
            'height': 402,
            'legend': 'right',
            'animation':{
              'duration': 1000,
              'easing': 'out',
              'startup': true
            },
          }
        });

        

        // Establish dependencies, declaring that 'filter' drives 'lineChart',
        // so that the pie chart will only display entries that are let through
        // given the chosen slider range.
        dashboard.bind(dateRangeSlider, lineChart);

        // Draw the dashboard.
        dashboard.draw(data);
        chartDayOfWeek.draw(dataDayOfWeek, optionsDayOfWeek);
        chartTimeOfDay.draw(dataTimeOfDay, optionsTimeOfDay);
      }
    
    </script>