config/routes.rb
Linkvan::Application.routes.draw do

  get 'api/facilities', to: 'api#all' #only enable if needed
  get 'api/facilities/filter/:scope', to: 'api#filtered'
  get 'api/facilities/filteredtest', to: 'api#filteredtest'
  get 'api/facilities/search', to: 'api#search'
  get 'api/facilities/:id', to: 'api#show'
  get 'api/getchanges', to: "api#getchanges"

  get "contact_form/new"
  get "contact_form/create"
  resource :session
  resources :users

  get 'facilities/options', to: 'facilities#options'
  get 'facilities/directions/:id', to: 'facilities#directions'
  get "facilities/filter/:scope" => "facilities#filtered", as: :filtered_facilities
  get 'facilities/filter/:scope/:latitude&:longitude', to: 'facilities#filtered', as: :coords_facilities
  get 'facilities/filter/:scope/:latitude&:longitude&:sortby&:hours&:services&:suitable&:welcome', to: 'facilities#filtered', as: :searched_facilities
  get 'facilities/search', to: 'facilities#search', as: :search_bar_facilities
  get 'crisis', to: 'crisis#index'
  get 'disclaimer', to: 'disclaimer#index'
  get 'about', to: 'about#index'
  get 'images', to: 'images#index'
  root 'facilities#index'
  get 'signup' => 'users#new'
  get "signin" => "sessions#new"
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  resources :facilities

end

app/helpers/facilities_helper.rb
module FacilitiesHelper

	def display_mon_hours(facility)
		if !facility.open_all_day_mon.nil? && facility.open_all_day_mon
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_mon.nil? && facility.closed_all_day_mon
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_mon.nil? && facility.closed_all_day_mon.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_mon
			content_tag(:h5, facility.startsmon_at.strftime("%I:%M%p") + " to " + facility.endsmon_at.strftime("%I:%M%p") + " and " + facility.startsmon_at2.strftime("%I:%M%p") + " to " + facility.endsmon_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startsmon_at.strftime("%I:%M%p") + " to " + facility.endsmon_at.strftime("%I:%M%p"))
		end
	end

	def display_tues_hours(facility)
		if !facility.open_all_day_tues.nil? && facility.open_all_day_tues
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_tues.nil? && facility.closed_all_day_tues
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_tues.nil? && facility.closed_all_day_tues.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_tues
			content_tag(:h5, facility.startstues_at.strftime("%I:%M%p") + " to " + facility.endstues_at.strftime("%I:%M%p") + " and " + facility.startstues_at2.strftime("%I:%M%p") + " to " + facility.endstues_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startstues_at.strftime("%I:%M%p") + " to " + facility.endstues_at.strftime("%I:%M%p"))
		end
	end

	def display_wed_hours(facility)
		if !facility.open_all_day_wed.nil? && facility.open_all_day_wed
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_wed.nil? && facility.closed_all_day_wed
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_wed.nil? && facility.closed_all_day_wed.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_wed
			content_tag(:h5, facility.startswed_at.strftime("%I:%M%p") + " to " + facility.endswed_at.strftime("%I:%M%p") + " and " + facility.startswed_at2.strftime("%I:%M%p") + " to " + facility.endswed_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startswed_at.strftime("%I:%M%p") + " to " + facility.endswed_at.strftime("%I:%M%p"))
		end
	end

	def display_thurs_hours(facility)
		if !facility.open_all_day_thurs.nil? && facility.open_all_day_thurs
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_thurs.nil? && facility.closed_all_day_thurs
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_thurs.nil? && facility.closed_all_day_thurs.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_thurs
			content_tag(:h5, facility.startsthurs_at.strftime("%I:%M%p") + " to " + facility.endsthurs_at.strftime("%I:%M%p") + " and " + facility.startsthurs_at2.strftime("%I:%M%p") + " to " + facility.endsthurs_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startsthurs_at.strftime("%I:%M%p") + " to " + facility.endsthurs_at.strftime("%I:%M%p"))
		end
	end

	def display_fri_hours(facility)
		if !facility.open_all_day_fri.nil? && facility.open_all_day_fri
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_fri.nil? && facility.closed_all_day_fri
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_fri.nil? && facility.closed_all_day_fri.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_fri
			content_tag(:h5, facility.startsfri_at.strftime("%I:%M%p") + " to " + facility.endsfri_at.strftime("%I:%M%p") + " and " + facility.startsfri_at2.strftime("%I:%M%p") + " to " + facility.endsfri_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startsfri_at.strftime("%I:%M%p") + " to " + facility.endsfri_at.strftime("%I:%M%p"))
		end
	end

	def display_sat_hours(facility)
		if !facility.open_all_day_sat.nil? && facility.open_all_day_sat
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_sat.nil? && facility.closed_all_day_sat
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_sat.nil? && facility.closed_all_day_sat.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_sat
			content_tag(:h5, facility.startssat_at.strftime("%I:%M%p") + " to " + facility.endssat_at.strftime("%I:%M%p") + " and " + facility.startssat_at2.strftime("%I:%M%p") + " to " + facility.endssat_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startssat_at.strftime("%I:%M%p") + " to " + facility.endssat_at.strftime("%I:%M%p"))
		end
	end

	def display_sun_hours(facility)
		if !facility.open_all_day_sun.nil? && facility.open_all_day_sun
			content_tag(:h5, "OPEN", class: "food-colour")
		elsif !facility.closed_all_day_sun.nil? && facility.closed_all_day_sun
			content_tag(:h5, "CLOSED", class: "medical-colour")
		elsif facility.closed_all_day_sun.nil? && facility.closed_all_day_sun.nil?
			content_tag(:h5, "BOTH ARE NIL")
		elsif facility.second_time_sun
			content_tag(:h5, facility.startssun_at.strftime("%I:%M%p") + " to " + facility.endssun_at.strftime("%I:%M%p") + " and " + facility.startssun_at2.strftime("%I:%M%p") + " to " + facility.endssun_at2.strftime("%I:%M%p"))
		else
			content_tag(:h5, facility.startssun_at.strftime("%I:%M%p") + " to " + facility.endssun_at.strftime("%I:%M%p"))
		end
	end

	def display_services(services_str)
		content_arr = ""
		services_arr = services_str.split(" ")
		services_arr.each do |s|
			case s
			when "Shelter"
   				content_arr += content_tag(:i, nil, class: "icon-sleepshelter_linkvan shelter-colour-index")
   			when "Food"
   				content_arr += content_tag(:i, nil, class: "glyphicon glyphicon-cutlery food-colour-index")
   			when "Medical"
   				content_arr += content_tag(:i, nil, class: "icon-Medical_linkvan medical-colour-index")
   			when "Hygiene"
   				content_arr += content_tag(:i, nil, class: "icon-hygiene_linkvan hygiene-colour-index")
   			when "Technology"
   				content_arr += content_tag(:i, nil, class: "icon-display technology-colour-index")
   			when "Advocacy"
   				content_arr += content_tag(:i, nil, class: "icon-Advocacy_linkvan legal-colour-index")
   			else

			end #ends case
		end

		return content_arr.html_safe
	end


	def resource_t_or_f?(t_or_f)
		if t_or_f
			content_tag(:i, nil, class: "glyphicon glyphicon-ok food-colour")
		else
			content_tag(:i, nil, class: "glyphicon glyphicon-remove medical-colour")
		end
	end

	def resource_icon_t_or_f?(res, t_or_f)
		case res
		when "id"
			if t_or_f
				content_tag(:i, nil, class: "icon-id_linkvan food-colour")
			else
				content_tag(:i, nil, class: "icon-id_linkvan medical-colour")
			end
		when "pets"
			if t_or_f
				content_tag(:i, nil, class: "icon-pets_linkvan food-colour")
			else
				content_tag(:i, nil, class: "icon-pets_linkvan medical-colour")
			end
		when "cart"
			if t_or_f
				content_tag(:i, nil, class: "icon-shoppingcart_linkvan food-colour")
			else
				content_tag(:i, nil, class: "icon-shoppingcart_linkvan medical-colour")
			end
		when "phone"
			if t_or_f
				content_tag(:i, nil, class: "icon-phone_linkvan food-colour")
			else
				content_tag(:i, nil, class: "icon-phone_linkvan medical-colour")
			end
		else
			if t_or_f
				content_tag(:i, nil, class: "icon-connection food-colour")
			else
				content_tag(:i, nil, class: "icon-connection medical-colour")
			end
		end
	end

	def resource_text_t_or_f?(res, t_or_f)
		case res
		when "id"
			if t_or_f
				content_tag(:h5, "ID IS required")
			else
				content_tag(:h5, "ID IS NOT required")
			end
		when "pets"
			if t_or_f
				content_tag(:h5, "Pets ARE allowed")
			else
				content_tag(:h5, "Pets ARE NOT allowed")
			end
		when "cart"
			if t_or_f
				content_tag(:h5, "Shopping carts ARE allowed")
			else
				content_tag(:h5, "Shopping carts ARE NOT allowed")
			end
		when "phone"
			if t_or_f
				content_tag(:h5, "Phones ARE available")
			else
				content_tag(:h5, "Phones ARE NOT available")
			end
		else
			if t_or_f
				content_tag(:h5, "Wi-Fi IS available")
			else
				content_tag(:h5, "Wi-Fi IS NOT available")
			end
		end
	end


	def format_tel(tel)
		if (tel[0] == "+")
			return tel.gsub("+1", "")
		else
			if (tel[0] != "1")
				tel.prepend("+1")
			end
			return tel.delete('-').gsub(/\s+/, "")
		end
		
	end

	def correct_user_or_admin?

  		if current_user.admin?
  			return true
  		else
  			current_user.facilities.each do |f|
  				if f.id == Facility.find(params[:id]).id
  					return true
  				end
  			end
  			return false
  		end
  	end



end

app/views/facilities/_nav.html.erb
	<nav role="navigation">

        <div class="nav-container">


						<form action="<%= search_bar_facilities_path %>" method="get" class="search-form" style="width: 280px; float: right; margin-top: 6px" >
							<%= submit_tag "SEARCH", :name => nil, class: "top-search-btn", style: "border-radius: 5px; float: right; margin-left: 5px;"%>
							<%= text_field_tag :search, nil, placeholder: "Search Facilities", style:
							"-webkit-border-radius: 5px;
							-moz-border-radius: 5px;
							border-radius: 5px;
							float: right;" %>

							
						</form>


						<a class="logo" href='/facilities' style="margin-right: 30px; display: inline; float: right; width: 30px">
							<%= image_tag('linkvan_horizontal.png') %>
			  		</a>

						<div class="pusher" style="float:left; min-width:300px; display:block; width: 50%"></div>


        </div>


  </nav>

app/views/facilities/index.html.erb
<%= render 'nav' %>

<div id="index-main">
	<h3>What service are you looking for?</h3>
</div>



<div class="admin-options">
    <!-- <strong>Prototype Status:</strong> <h4 style="color:green">Ready</h4> -->
    <!-- <strong>Developer Note:</strong> No critical issues</br> -->
    <!-- <strong>Volunteer Note:</strong> New category added - Advocacy</br> -->
    <br>
    <br>

    <% if current_user_admin? %>
        <%= link_to "Add New Facility", new_facility_path %><br>
    <%end%>

    <% if current_user %>
        Welcome back, <%= link_to current_user.name, current_user %>!<br>
        
        <%= link_to "Sign Out", session_path, method: :delete %>
    <%else%>
        <%= link_to 'Sign In', signin_path%>
				|
				<%= link_to "Disclaimer", disclaimer_path %>
				|
				<%= link_to "About Us", about_path%>
                |
                <%= link_to 'Sign Up', signup_path%>
    <%end%>
</div>


<p id="demo"></p>

<script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

<script>

var latitude, longitude;
var hasStoredLatLon = false;


var x = document.getElementById("demo");

    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }


function showPosition(position) {
    //x.innerHTML = "Latitude: " + position.coords.latitude +
    //"<br>Longitude: " + position.coords.longitude;
    latitude = position.coords.latitude;
    longitude = position.coords.longitude;

		// TODO add cookies
		//if (hasStoredLatLon === false) {
			//hasStoredLatLon = true;
			//var storedLat = latitude.toFixed(4);
			//var storedLon = longitude.toFixed(4);
		//} else {}
}

setTimeout(function(){

    //Create Shelter

    var divid = document.getElementById("index-main");
    var bshelter = document.createElement("button");
    var tshelter = document.createElement("p");
    tshelter.innerHTML = "Shelter";
    tshelter.setAttribute("class", "button-text");

    var shelterImg=document.createElement("i");
    //shelterImg.setAttribute("class", "glyphicon glyphicon-home shelter-colour");
    shelterImg.setAttribute("font-family", "Project-Linkvan");
    shelterImg.setAttribute("class", "icon-sleepshelter_linkvan shelter-colour");

    var shelterChev=document.createElement("i");
    shelterChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");
    bshelter.appendChild(shelterImg);
    bshelter.appendChild(tshelter);
    bshelter.appendChild(shelterChev);

    bshelter.setAttribute("class", "btn");
    bshelter.onclick = function() { // Note this is a function
        window.location = "/facilities/filter/Shelter/?latitude=" + latitude + "&longitude="+longitude;
    };

    divid.appendChild(bshelter);


//Create Food
    var bfood = document.createElement("button");
    var tfood = document.createElement("p");
    tfood.innerHTML = "Food"
    tfood.setAttribute("class", "button-text");

    var foodImg=document.createElement("i");
    foodImg.setAttribute("class", "glyphicon glyphicon-cutlery food-colour");

    var foodChev=document.createElement("i");
    foodChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    bfood.appendChild(foodImg);
    bfood.appendChild(tfood);
    bfood.appendChild(foodChev);

    bfood.setAttribute("class", "btn");
    bfood.onclick = function() { // Note this is a function
        window.location = "/facilities/filter/Food/?latitude=" + latitude + "&longitude="+longitude;
    };

    divid.appendChild(bfood);

//Create Medical
    var bmedical = document.createElement("button");
    var tmedical = document.createElement("p");
    tmedical.innerHTML = "Medical"
    tmedical.setAttribute("class", "button-text");

    var medicalImg=document.createElement("i");
    //medicalImg.setAttribute("class", "glyphicon glyphicon-heart-empty medical-colour");
    medicalImg.setAttribute("font-family", "Project-Linkvan");
    medicalImg.setAttribute("class", "icon-Medical_linkvan medical-colour");

    var medicalChev=document.createElement("i");
    medicalChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    bmedical.appendChild(medicalImg);
    bmedical.appendChild(tmedical);
    bmedical.appendChild(medicalChev);

    bmedical.setAttribute("class", "btn");
    bmedical.onclick = function() { // Note this is a function
        window.location = "/facilities/filter/Medical/?latitude=" + latitude + "&longitude="+longitude;
    };

    divid.appendChild(bmedical);

//Create Hygiene
    var bhygiene = document.createElement("button");
    var thygiene = document.createElement("p");
    thygiene.innerHTML = "Hygiene"
    thygiene.setAttribute("class", "button-text");

    var hygieneImg=document.createElement("i");
    //hygieneImg.setAttribute("class", "glyphicon glyphicon-tint hygiene-colour");
    hygieneImg.setAttribute("font-family", "Project-Linkvan");
    hygieneImg.setAttribute("class", "icon-hygiene_linkvan hygiene-colour");


    var hygieneChev=document.createElement("i");
    hygieneChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    bhygiene.appendChild(hygieneImg);
    bhygiene.appendChild(thygiene);
    bhygiene.appendChild(hygieneChev);

    bhygiene.setAttribute("class", "btn");
    bhygiene.onclick = function() { // Note this is a function
        window.location = "/facilities/filter/Hygiene/?latitude=" + latitude + "&longitude="+longitude;
    };

    divid.appendChild(bhygiene);

//Create Technology
    var btech = document.createElement("button");
    var ttech = document.createElement("p");
    ttech.innerHTML = "Technology"
    ttech.setAttribute("class", "button-text");

    var techImg=document.createElement("i");
    //techImg.setAttribute("class", "glyphicon glyphicon-globe technology-colour");
    techImg.setAttribute("font-family", "Project-Linkvan");
    techImg.setAttribute("class", "icon-display technology-colour");


    var techChev=document.createElement("i");
    techChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    btech.appendChild(techImg);
    btech.appendChild(ttech);
    btech.appendChild(techChev);

    btech.setAttribute("class", "btn");
    btech.onclick = function() { // Note this is a function
        window.location = "/facilities/filter/Technology/?latitude=" + latitude + "&longitude="+longitude;
    };

    divid.appendChild(btech);

//Create Legal
    var blegal = document.createElement("button");
    var tlegal = document.createElement("p");
    tlegal.innerHTML = "Advocacy";
    tlegal.setAttribute("class", "button-text");

    var legalImg=document.createElement("i");
    //legalImg.setAttribute("class", "glyphicon glyphicon-briefcase medical-colour");
    legalImg.setAttribute("font-family", "Project-Linkvan");
    legalImg.setAttribute("class", "icon-Advocacy_linkvan legal-colour");


    var legalChev=document.createElement("i");
    legalChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    blegal.appendChild(legalImg);
    blegal.appendChild(tlegal);
    blegal.appendChild(legalChev);

    blegal.setAttribute("class", "btn");
    blegal.onclick = function() { // Note this is a function
        window.location = "/facilities/filter/Legal/?latitude=" + latitude + "&longitude="+longitude;
    };

    divid.appendChild(blegal);

//Create Crisis
    var bcrisis = document.createElement("button");
    var tcrisis = document.createElement("p");

    tcrisis.innerHTML = "&nbsp;Crisis Lines";
    tcrisis.setAttribute("class", "button-text");

    var crisisImg=document.createElement("i");
    crisisImg.setAttribute("class", "glyphicon glyphicon-warning-sign crisis-colour");

    var crisisChev=document.createElement("i");
    crisisChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    
    bcrisis.appendChild(crisisImg);

    bcrisis.appendChild(tcrisis);
    bcrisis.appendChild(crisisChev);

    bcrisis.setAttribute("class", "btn");
    bcrisis.onclick = function() { // Note this is a function
        window.location = "/crisis";
    };

    divid.appendChild(bcrisis);

}, 1200);


</script>

app/views/facilities/search.html.erb
<%= render 'nav' %>
<br>
<br>

<div id="index">
<% if @facilities.present? %>
<div id="search_results">
  <h3><%= pluralize(@facilities.count, 'result') %> for "<%= params[:search] %>"</h3>
</div>
<% @facilities.each do |f| %>
<a href=<%= facility_path(f)%>>
  <div class="facility-block">
    <div class= "facility-block-name"><strong><%= f.name %></strong></div>
    <%= display_services(f.services) %>
    <i class="glyphicon glyphicon-chevron-right chevron-right-filtered"></i>
  </div>
</a>
  <hr>
<% end %>

<% else %>
  <p>There are no facilities containing <%= params[:search] %>.</p>
<% end %>
</div>

app/views/facilities/show.html.erb
<%= render 'nav' %>

<div id="index-main">
<h1><%=@facility.name %></h1>


<h2>Welcome</h2>
<div class="inset">
  <p><%=@facility.welcomes %></p>
</div>


<h2>Services</h2>
<div class="inset">
  <p><%=display_services(@facility.services) %></p>
</div>

<div class="inset-gmap">
  <div id="map-canvas"></div>
  <p><%=@facility.address %></p>
</div>

<div class="inset-call">
  <!--<strong>Call:</strong> <a href="tel:+17788853580">778-885-3580</a>-->
  <strong>Call:</strong> <a href="tel:<%=format_tel(@facility.phone) %>"><%=format_tel(@facility.phone) %></a>
</div> <!--ends inset-call -->

<!--max=71-->
<div class="inset-website">
  <p><strong>Website: </strong> <%= link_to truncate(@facility.website, length: 33), "http://" + @facility.website  %></p>
</div>

<div id="inset-directions">
</div>

<div class="description">

<!--
  <h2>Resources (In Progress)</h2>

<table>
  <tr>
    <td><%= resource_icon_t_or_f?("id", @facility.r_id) %></td>
    <td><%=resource_t_or_f?(@facility.r_id)%></td>
    <td><%=resource_text_t_or_f?("id", @facility.r_id)%></td>
  </tr>
  <tr>
    <td><%= resource_icon_t_or_f?("pets", @facility.r_pets) %></td>
    <td><%=resource_t_or_f?(@facility.r_pets)%> </td>
    <td><%=resource_text_t_or_f?("pets", @facility.r_pets)%></td>
  </tr>
  <tr>
    <td><%= resource_icon_t_or_f?("cart", @facility.r_cart) %></td>
    <td><%=resource_t_or_f?(@facility.r_cart)%></td>
    <td><%=resource_text_t_or_f?("cart", @facility.r_cart)%></td>
  </tr>
  <tr>
    <td><%= resource_icon_t_or_f?("phone", @facility.r_phone) %></td>
    <td><%=resource_t_or_f?(@facility.r_phone)%></td>
    <td> <%=resource_text_t_or_f?("phone", @facility.r_phone)%></td>
  </tr>
  <tr>
    <td><%= resource_icon_t_or_f?("wifi", @facility.r_wifi) %></td>
    <td><%=resource_t_or_f?(@facility.r_wifi)%></td>
    <td><%=resource_text_t_or_f?("wifi", @facility.r_wifi)%></td>
  </tr>
</table>
-->

  <h2>Hours</h2>

<table>
  <tr>
    <td>Monday:</td>
    <td><%= display_mon_hours(@facility) %></td>
  </tr>
  <tr>
    <td>Tuesday:</td>
    <td><%= display_tues_hours(@facility) %></td>
  </tr>
  <tr>
    <td>Wednesday:</td>
    <td><%= display_wed_hours(@facility) %></td>
  </tr>
  <tr>
    <td>Thursday:</td>
    <td><%= display_thurs_hours(@facility) %></td>
  </tr>
  <tr>
    <td>Friday:</td>
    <td><%= display_fri_hours(@facility) %></td>
  </tr>
  <tr>
    <td>Saturday:</td>
    <td><%= display_sat_hours(@facility) %> </td>
  </tr>
  <tr>
    <td>Sunday:</td>
    <td><%= display_sun_hours(@facility) %> </td>
  </tr>
</table>

<div class="notes">
  <strong>Notes:</strong><br>
  <p><%= @facility.notes %></p>
</div>


</div>


<% if correct_user_or_admin? %>
  <%= link_to "Edit", edit_facility_path%>
  <% if current_user_admin? %>
    <%= link_to "Delete", @facility, method: :delete, data: {confirm: 'Are you sure?'}%>
  <% end %>
<% end %>
</div>




<%= content_tag :div, class: "temp_information", data: {jsevent: @facility} do %>
<% end %>

<script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script>
var jsevent = $('.temp_information').data('jsevent');
var map;
var latitude, longitude;




function initialize() {
  var myLocation = new google.maps.LatLng(jsevent.lat, jsevent.long);

        var mapOptions = {
          center: myLocation,
          zoom: 13
        };

        var marker = new google.maps.Marker({
      		position: myLocation,
      		animation: google.maps.Animation.DROP,
      		title: jsevent.name});



  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  marker.setMap(map);
}

google.maps.event.addDomListener(window, 'load', initialize);




setTimeout(function(){
    var divid = document.getElementById("inset-directions");
    var bdirections = document.createElement("button");
    var tdirections = document.createElement("p");
    tdirections.innerHTML = "Directions"
    tdirections.setAttribute("class", "button-text");

    var directionsImg=document.createElement("i");
    directionsImg.setAttribute("class", "glyphicon glyphicon-search directions-colour");

    var directionsChev=document.createElement("i");
    directionsChev.setAttribute("class", "glyphicon glyphicon-chevron-right chevron-right");

    bdirections.appendChild(directionsImg);
    bdirections.appendChild(tdirections);
    bdirections.appendChild(directionsChev);
    bdirections.setAttribute("class", "btn");
    bdirections.onclick = function() { // Note this is a function
      window.location = "/facilities/directions/" + jsevent.id;
    };

    divid.appendChild(bdirections);
}, 500);



</script>